version: "3.8"

services:
  rabbitmq:
    build: docker/rabbitmq
    ports:
      - "15672:15672"
      - "15674:15674"
      - "5672:5672"

  web:
    build:
      dockerfile: docker/web/Dockerfile
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq