version: "3.8"

services:
  rabbitmq:
    build: docker/Dockerfile.rabbitmq
    ports:
      - "15672:15672"
      - "15674:15674"
      - "5672:5672"
    networks:
      - default

  web:
    build:
      dockerfile: docker/Dockerfile.app
      context: .
    ports:
      - "8080:3000"
    depends_on:
      - rabbitmq
    command: [ "yarn", "workspace", "web", "start" ]
    networks:
      - default

  app:
    build:
      dockerfile: docker/Dockerfile.app
      context: .
    ports:
      - "8081:3000"
    depends_on:
      - rabbitmq
    command: [ "yarn", "workspace", "app", "start" ]
    networks:
      - default

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123root
    volumes:
      - mongodb-data:/data/db
    networks:
      - default

volumes:
  mongodb-data:

networks:
  default:
