version: "3.8"

services:
  rabbitmq:
    build:
      dockerfile: docker/Dockerfile.rabbitmq
    ports:
      - "15672:15672"
      - "15674:15674"
      - "5672:5672"

  base_service:
    build:
      dockerfile: docker/Dockerfile.app
      context: .
    image: rabbit_chat:latest
    

  web:
    image: rabbit_chat:latest
    ports:
      - "8080:3200"
    depends_on:
      - base_service
      - rabbitmq
    command: [ "yarn", "workspace", "web", "start" ]

  app:
    image: rabbit_chat:latest
    ports:
      - "8081:3201"
    depends_on:
      - base_service
      - rabbitmq
    command: [ "yarn", "workspace", "app", "start" ]

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123root
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:


