parser: '@typescript-eslint/parser'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
plugins:
  - '@typescript-eslint'
env:
  node: true
  es6: true
  browser: true
parserOptions:
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: 'detect'
rules:
  react/prop-types: 'off' # TypeScriptを使用しているため、propTypesのチェックは不要
