parser: "@typescript-eslint/parser"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:react/recommended"
plugins:
  - "@typescript-eslint"
  - "react"
env:
  node: true
  es6: true
  browser: true
parserOptions:
  ecmaFeatures:
    jsx: true
settings:
  react:
    version: "detect"
rules:
  react/prop-types: "off" # TypeScriptを使用しているため、propTypesのチェックは不要
  react/react-in-jsx-scope: "off" # Next.jsを使用しているため、Reactのimportは不要

